[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100
src_paths = ["./python/", "./python/tests/kat/"]

[tool.pytest.ini_options]
pythonpath = ["python"]
filterwarnings = [
  "ignore:.*The metaschema specified by \\$schema was not found.*:DeprecationWarning",
  "ignore:.*Call to deprecated create function Descriptor.*:DeprecationWarning",
  "ignore:.*Call to deprecated create function FileDescriptor.*:DeprecationWarning",
  "ignore:.*Call to deprecated create function FieldDescriptor.*:DeprecationWarning",
]
testpaths = ["python/tests"]
norecursedirs = "docs"
markers = "compilertest"
